/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PACKED_BIO_H_RPCGEN
#define _PACKED_BIO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define NB_CUSTOMER 10
#define BIRTH_DATE_LEN 11
#define BUF_LEN 20

enum typeOffer {
	UNKNOWN_OFFER = 0,
	PACKED_VEGETABLES = 1,
	FISH_RECIPES = 2,
	PACKED_FRUITS = 3,
};
typedef enum typeOffer typeOffer;

enum supplierType {
	UNKOWN_SUPPLIER = 0,
	VEGETABLES_SUPPLIER = 1,
	FISH_SUPPLIER = 2,
	FRUITS_SUPPLIER = 3,
};
typedef enum supplierType supplierType;

struct customer {
	int id;
	char birth_date[BIRTH_DATE_LEN];
	char name[BUF_LEN];
	char surname[BUF_LEN];
	char address[BUF_LEN];
};
typedef struct customer customer;

struct offer {
	int id;
	enum typeOffer type;
	double price;
	u_short nb;
};
typedef struct offer offer;

struct anyCustomers {
	struct customer customers[10];
	u_int len;
};
typedef struct anyCustomers anyCustomers;

struct anyOffers {
	struct offer offers[10];
	u_int len;
};
typedef struct anyOffers anyOffers;

struct supplier {
	int id;
	char surname[BUF_LEN];
	char address[BUF_LEN];
	enum supplierType type;
};
typedef struct supplier supplier;

struct anySuppliers {
	struct supplier suppliers[10];
	u_int len;
};
typedef struct anySuppliers anySuppliers;

#define PACKED_BIO 0x23456789
#define PACKED_BIO_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define CUSTOMER_UPDATE_OR_CREATE 1
extern  int * customer_update_or_create_1(customer *, CLIENT *);
extern  int * customer_update_or_create_1_svc(customer *, struct svc_req *);
#define CUSTOMER_GET 2
extern  customer * customer_get_1(int *, CLIENT *);
extern  customer * customer_get_1_svc(int *, struct svc_req *);
#define CUSTOMER_GET_ALL 3
extern  anyCustomers * customer_get_all_1(void *, CLIENT *);
extern  anyCustomers * customer_get_all_1_svc(void *, struct svc_req *);
#define OFFER_GET 4
extern  offer * offer_get_1(int *, CLIENT *);
extern  offer * offer_get_1_svc(int *, struct svc_req *);
#define OFFER_CREATE 5
extern  int * offer_create_1(offer *, CLIENT *);
extern  int * offer_create_1_svc(offer *, struct svc_req *);
#define OFFER_DELETE 6
extern  int * offer_delete_1(int *, CLIENT *);
extern  int * offer_delete_1_svc(int *, struct svc_req *);
#define OFFER_GET_ALL 7
extern  anyOffers * offer_get_all_1(void *, CLIENT *);
extern  anyOffers * offer_get_all_1_svc(void *, struct svc_req *);
#define INIT 8
extern  void * init_1(void *, CLIENT *);
extern  void * init_1_svc(void *, struct svc_req *);
#define SUPPLIER_CREATE 9
extern  int * supplier_create_1(supplier *, CLIENT *);
extern  int * supplier_create_1_svc(supplier *, struct svc_req *);
#define SUPPLIER_GET 10
extern  supplier * supplier_get_1(int *, CLIENT *);
extern  supplier * supplier_get_1_svc(int *, struct svc_req *);
#define SUPPLIER_DELETE 11
extern  int * supplier_delete_1(int *, CLIENT *);
extern  int * supplier_delete_1_svc(int *, struct svc_req *);
#define SUPPLIER_GET_ALL 12
extern  anySuppliers * supplier_get_all_1(supplierType *, CLIENT *);
extern  anySuppliers * supplier_get_all_1_svc(supplierType *, struct svc_req *);
extern int packed_bio_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CUSTOMER_UPDATE_OR_CREATE 1
extern  int * customer_update_or_create_1();
extern  int * customer_update_or_create_1_svc();
#define CUSTOMER_GET 2
extern  customer * customer_get_1();
extern  customer * customer_get_1_svc();
#define CUSTOMER_GET_ALL 3
extern  anyCustomers * customer_get_all_1();
extern  anyCustomers * customer_get_all_1_svc();
#define OFFER_GET 4
extern  offer * offer_get_1();
extern  offer * offer_get_1_svc();
#define OFFER_CREATE 5
extern  int * offer_create_1();
extern  int * offer_create_1_svc();
#define OFFER_DELETE 6
extern  int * offer_delete_1();
extern  int * offer_delete_1_svc();
#define OFFER_GET_ALL 7
extern  anyOffers * offer_get_all_1();
extern  anyOffers * offer_get_all_1_svc();
#define INIT 8
extern  void * init_1();
extern  void * init_1_svc();
#define SUPPLIER_CREATE 9
extern  int * supplier_create_1();
extern  int * supplier_create_1_svc();
#define SUPPLIER_GET 10
extern  supplier * supplier_get_1();
extern  supplier * supplier_get_1_svc();
#define SUPPLIER_DELETE 11
extern  int * supplier_delete_1();
extern  int * supplier_delete_1_svc();
#define SUPPLIER_GET_ALL 12
extern  anySuppliers * supplier_get_all_1();
extern  anySuppliers * supplier_get_all_1_svc();
extern int packed_bio_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_typeOffer (XDR *, typeOffer*);
extern  bool_t xdr_supplierType (XDR *, supplierType*);
extern  bool_t xdr_customer (XDR *, customer*);
extern  bool_t xdr_offer (XDR *, offer*);
extern  bool_t xdr_anyCustomers (XDR *, anyCustomers*);
extern  bool_t xdr_anyOffers (XDR *, anyOffers*);
extern  bool_t xdr_supplier (XDR *, supplier*);
extern  bool_t xdr_anySuppliers (XDR *, anySuppliers*);

#else /* K&R C */
extern bool_t xdr_typeOffer ();
extern bool_t xdr_supplierType ();
extern bool_t xdr_customer ();
extern bool_t xdr_offer ();
extern bool_t xdr_anyCustomers ();
extern bool_t xdr_anyOffers ();
extern bool_t xdr_supplier ();
extern bool_t xdr_anySuppliers ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PACKED_BIO_H_RPCGEN */
