/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "packed_bio.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

int *
customer_update_or_create_1(customer *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, CUSTOMER_UPDATE_OR_CREATE,
		(xdrproc_t) xdr_customer, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

customer *
customer_get_1(int *argp, CLIENT *clnt)
{
	static customer clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, CUSTOMER_GET,
		(xdrproc_t) xdr_int, (caddr_t) argp,
		(xdrproc_t) xdr_customer, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

offer *
offer_get_1(int *argp, CLIENT *clnt)
{
	static offer clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, OFFER_GET,
		(xdrproc_t) xdr_int, (caddr_t) argp,
		(xdrproc_t) xdr_offer, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

offer *
offer_create_1(offer *argp, CLIENT *clnt)
{
	static offer clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, OFFER_CREATE,
		(xdrproc_t) xdr_offer, (caddr_t) argp,
		(xdrproc_t) xdr_offer, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
offre_delete_1(offer *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, OFFRE_DELETE,
		(xdrproc_t) xdr_offer, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
