/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "packed_bio.h"

#define CUSTOMER_MAX 10
#define OFFER_MAX 10

unsigned customers_count = 0;
customer customers[CUSTOMER_MAX];

offer offers[OFFER_MAX];
unsigned offers_count = 0;

int customer_find_index(customer *c)
{
    unsigned i;
    for(i = 0; i < customers_count; i++) {
        if (strcmp(customers[i].name, c->name) == 0
            && strcmp(customers[i].surname, c->surname) == 0
            && strcmp(customers[i].address, c->address) == 0)
                return i;
    }
    return -1;
}

int offer_find_index(offer *o)
{
    unsigned i;
    for(i = 0; i < offers_count; i++) {
        if (o->type == offers[i].type && o->price == offers[i].price && o->nb == o->nb) {
            return i;
        }
    }
    return -1;
}

int *
customer_update_or_create_1_svc(customer *argp, struct svc_req *rqstp)
{
    static int  result = -1;

    if (argp == NULL) return &result;

    if (argp->id == -1) {
        if (customers_count + 1 < CUSTOMER_MAX && customer_find_index(argp) == -1) {
            argp->id = customers_count;
            customers[customers_count] = *argp;
            result = customers_count++;
        }
    } else if (argp->id < customers_count) {
        if (customer_find_index(argp) != -1) {
            return &result;
        }
        customers[argp->id] = *argp;
        result = argp->id;
    }

    return &result;
}

customer *
customer_get_1_svc(int *id, struct svc_req *rqstp)
{
	static customer  result;

    if (id != NULL && *id >= 0 && *id < customers_count) {
        result = customers[*id];
    } else {
        result.id = -1;
    }

	return &result;
}
anyCustomers *
customer_get_all_1_svc(void *argp, struct svc_req *rqstp)
{
    static anyCustomers result;
    unsigned i;

    for(i = 0; i < customers_count; i++) {
        result.customers[i] = customers[i];
    }
    result.len = customers_count;

    return &result;
}

offer *
offer_get_1_svc(int *id, struct svc_req *rqstp)
{
	static offer  result;
    unsigned i;

    if (id != NULL) {
        for(i = 0; i < OFFER_MAX; i++) {
            if (offers[i].id == *id) {
                result = offers[*id];
                return &result;
            }
        }
    }
    result.id = -1;

	return &result;
}

int *
offer_create_1_svc(offer *o, struct svc_req *rqstp)
{
	static int  result = -1;
    unsigned i;

    if (o == NULL || offer_find_index(o) != -1) 
        return &result;

    if (o->id < 0) {
        for(i = 0; i < OFFER_MAX; i++) {
            if (offers[i].id == -1) {
                o->id = offers_count;
                offers[i] = *o;
                result = offers_count++;
                return &result;
            }
        }
    } else {
        for(i = 0; i < OFFER_MAX; i++) {
            if (offers[i].id == o->id) {
                offers[i] = *o;
                result = o->id;
            }
        }
    }

	return &result;
}

int *
offer_delete_1_svc(int *id, struct svc_req *rqstp)
{
	static int  result = -1;
    unsigned i;

    if (id == NULL || *id < 0) 
        return &result;

    for(i = 0; i < OFFER_MAX; i++) {
        if (offers[i].id == *id) {
            offers[i].id = -1;
	        result = *id;
            return &result;
        }
    }

	return &result;
}

anyOffers *
offer_get_all_1_svc(void *argp, struct svc_req *rqstp)
{
    static anyOffers result;
    unsigned i;

    result.len = 0;
    for(i = 0; i < OFFER_MAX; i++) {
        if (offers[i].id != -1) {
            result.offers[result.len++] = offers[i];
        }
    }

    return &result;
}

void *
init_1_svc(void *argp, struct svc_req *rqstp)
{
    static char result;
    unsigned i;

    for(i = 0; i < OFFER_MAX; i++) {
        offers[i].id = -1;
    }

    return (void *) &result;
}
