/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <assert.h>

#include "packed_bio.h"


void
packed_bio_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	customer  customer_update_or_create_1_arg;
	customer  *result_2;
	int  customer_get_1_arg;
	offer  *result_3;
	int  offer_get_1_arg;
	offer  *result_4;
	offer  offer_create_1_arg;
	int  *result_5;
	offer  offre_delete_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, PACKED_BIO, PACKED_BIO_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

void customer_init(customer *c)
{
    if (c == NULL) return;

    c->id = -1;
    c->birth_date[0] = '\0';
    c->name[0] = '\0';
    c->surname[0] = '\0';
    c->address[0] = '\0';
}

void customer_display(customer *c)
{
    printf("Client :\n");
    printf("\tId = %d\n", c->id);
    printf("\tDate de naissance = %s\n", c->birth_date);
    printf("\tPrénom = %s\n", c->name);
    printf("\tNom = %s\n", c->surname);
    printf("\tAdresse = %s\n", c->address);
}

void offer_init(offer *o)
{
    o->id = -1;
    o->price = -1;
    o->type = UNKNOWN_OFFER;
	o->nb = 0;
}

void offer_display(offer *o) {
	printf("Offre :\n");
	printf("\tId = %d\n", o->id);
	printf("\tPrix = %.2f\n", o->price);
	switch (o->type) {
		case UNKNOWN_OFFER:
			printf("\tType = Offre inconnue\n");
			break;
		case PACKED_VEGETABLES:
			printf("\tType = Panier de légume\n");
			break;
		case FISH_RECIPES:
			printf("\tType = Assortiments de poissons\n");
			printf("\tNombre de personne : %hu\n", o->nb);
			break;
		case PACKED_FRUITS:
			printf("\tType = Panier de fruit\n");
			printf("\tNombre de fruits : %hu\n", o->nb);
			break;
	}
}

void supplier_init(supplier *s)
{
	s->address[0] = '\0';
	s->id = -1;
	s->surname[0] = '\0';
	s->type = UNKOWN_SUPPLIER;
}

void supplier_display(supplier *s)
{
	printf("Fournisseur\n");
	printf("\tId = %d\n", s->id);
	printf("\tNom = %s\n", s->surname);
	printf("\tAdresse = %s\n", s->address);
	switch (s->type) {
		case UNKOWN_SUPPLIER:
			printf("\tType = Inconnue\n");
			break;
		case VEGETABLES_SUPPLIER:
			printf("\tType = Légume\n");
			break;
		case FISH_SUPPLIER:
			printf("\tType = Poissons\n");
			break;
		case FRUITS_SUPPLIER:
			printf("\tType = Fruits\n");
			break;
	}
}

int packed_bio_customers(CLIENT *clnt)
{
    int *res, i;
    customer c, *c2;
    anyCustomers *cs;

	offer o, *o2;
    anyOffers *os;

	supplier s, *s2;
	anySuppliers *ss;
	supplierType st;

    // New customers
    customer_init(&c);
    sprintf(c.name, "Nonnon");
    sprintf(c.surname, "Yaya");
    sprintf(c.birth_date, "23/03/98");
    sprintf(c.address, "Mimosa");
    res = customer_update_or_create_1(&c, clnt);
    assert(*res != -1);

    customer_init(&c);
    sprintf(c.surname, "Etchebest");
    sprintf(c.name, "Philippe");
    sprintf(c.birth_date, "02/12/66");
    sprintf(c.address, "Aisne");
    res = customer_update_or_create_1(&c, clnt);
    assert(*res != -1);

    // Update customer
    customer_init(&c);
    c.id = *res;
    sprintf(c.surname, "Des champs");
    sprintf(c.name, "Didier");
    sprintf(c.birth_date, "15/10/68");
    sprintf(c.address, "Bayonne");
    res = customer_update_or_create_1(&c, clnt);
    assert(*res != -1);

    cs = customer_get_all_1(NULL, clnt);
    for(i = 0; i < cs->len; i++) {
        customer_display(cs->customers + i);
    }

    init_1(NULL, clnt);
	// Create offers
    printf("Création d'un panier de légume\n");
	offer_init(&o);
	o.price = 16.;
	o.type = PACKED_VEGETABLES;
	res = offer_create_1(&o, clnt);
	o2 = offer_get_1(res, clnt);
    offer_display(o2);

    printf("Création d'un panier de fruit\n");
	offer_init(&o);
	o.price = 19.99;
	o.type = PACKED_FRUITS;
	o.nb = 3;
	res = offer_create_1(&o, clnt);
	o2 = offer_get_1(res, clnt);
    offer_display(o2);

    printf("Création d'un assortiment de poissons\n");
	offer_init(&o);
	o.price = 32.5;
	o.type = FISH_RECIPES;
	o.nb = 6;
	res = offer_create_1(&o, clnt);
	o2 = offer_get_1(res, clnt);
    offer_display(o2);

	// Delete offer
	i = 0;
    printf("On supprime l'offre %d\n", i);
	res = offer_delete_1(&i, clnt);

    printf("Maintenant il doit avoir une offre en moins\n");
    os = offer_get_all_1(NULL, clnt);
    for(i = 0; i < os->len; i++) {
        offer_display(os->offers + i);
    }

	printf("Création d'un fournisseur de fruit\n");
	supplier_init(&s);
	sprintf(s.address, "Pont-Croix");
	sprintf(s.surname, "Pierre");
	s.type = FRUITS_SUPPLIER;
	res = supplier_create_1(&s, clnt);
	s2 = supplier_get_1(res, clnt);
	supplier_display(s2);

	printf("Création d'un fournisseur de légume\n");
	supplier_init(&s);
	sprintf(s.address, "Audierne");
	sprintf(s.surname, "Jacques");
	s.type = VEGETABLES_SUPPLIER;
	res = supplier_create_1(&s, clnt);
	s2 = supplier_get_1(res, clnt);
	supplier_display(s2);

	printf("Création d'un deuxième fournisseur de fruit\n");
	supplier_init(&s);
	sprintf(s.address, "Douarnenez");
	sprintf(s.surname, "Paul");
	s.type = FRUITS_SUPPLIER;
	res = supplier_create_1(&s, clnt);
	s2 = supplier_get_1(res, clnt);
	supplier_display(s2);

	printf("On affiche tout les fournisseurs de fruit (2)\n");
	st = FRUITS_SUPPLIER;
	ss = supplier_get_all_1(&st, clnt);
	for (i = 0; i < ss->len; i++) {
		supplier_display(ss->suppliers + i);
	}

	printf("On affiche tout les fournisseurs (3)\n");
	st = UNKNOWN_OFFER;
	ss = supplier_get_all_1(&st, clnt);
	for (i = 0; i < ss->len; i++) {
		supplier_display(ss->suppliers + i);
	}

    return 0;
}

int main (int argc, char *argv[])
{
	char *host;
	if (argc < 2) {
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	packed_bio_1(host);
    exit(packed_bio_customers(clnt_create(host, PACKED_BIO, PACKED_BIO_VER, "udp")));
}
