/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "packed_bio.h"


void
packed_bio_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	customer  customer_update_or_create_1_arg;
	customer  *result_2;
	int  customer_get_1_arg;
	offer  *result_3;
	int  offer_get_1_arg;
	offer  *result_4;
	offer  offer_create_1_arg;
	int  *result_5;
	offer  offre_delete_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, PACKED_BIO, PACKED_BIO_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int main (int argc, char *argv[])
{
	char *host;
    CLIENT *clnt;
    int *res;
    customer c, *c2;

	if (argc < 2) {
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	packed_bio_1(host);
	clnt = clnt_create(host, PACKED_BIO, PACKED_BIO_VER, "udp");

    c.id = -1;
    sprintf(c.birth_date, "23");
    sprintf(c.name, "Nonnon");
    sprintf(c.surname, "Yaya");
    sprintf(c.address, "Mimosa");
    res = customer_update_or_create_1(&c, clnt);
    c2 = customer_get_1(res, clnt);
    printf("prenom = %s\n", c2->name);

    exit(0);
}
